export const COUNTRIES = [
  { value: 'Argentina', label: 'Argentina' },
  { value: 'Ecuador', label: 'Ecuador' },
  { value: 'El Salvador', label: 'El Salvador' },
  { value: 'Guatemala', label: 'Guatemala' },
  { value: 'Honduras', label: 'Honduras' },
  { value: 'Nicaragua', label: 'Nicaragua' },
  { value: 'Costa Rica', label: 'Costa Rica' },
  { value: 'Panamá', label: 'Panamá' },
  { value: 'México', label: 'México' },
  { value: 'Estados Unidos', label: 'Estados Unidos' },
  { value: 'Canadá', label: 'Canadá' },
  { value: 'Colombia', label: 'Colombia' },
  { value: 'Venezuela', label: 'Venezuela' },
  { value: 'Perú', label: 'Perú' },
  { value: 'Bolivia', label: 'Bolivia' },
  { value: 'Chile', label: 'Chile' },
  { value: 'Uruguay', label: 'Uruguay' },
  { value: 'Paraguay', label: 'Paraguay' },
  { value: 'Brasil', label: 'Brasil' },
  { value: 'República Dominicana', label: 'República Dominicana' },
  { value: 'Cuba', label: 'Cuba' },
  { value: 'Puerto Rico', label: 'Puerto Rico' },
  { value: 'España', label: 'España' },
  { value: 'Otro', label: 'Otro' },
]
