/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PayResponseIndexRouteImport } from './routes/pay-response/index'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as DashboardUsersRouteImport } from './routes/dashboard.users'
import { Route as DashboardProductsRouteImport } from './routes/dashboard.products'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardCategoriesRouteImport } from './routes/dashboard.categories'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DashboardProductsNewRouteImport } from './routes/dashboard.products.new'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin.orders.$orderId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayResponseIndexRoute = PayResponseIndexRouteImport.update({
  id: '/pay-response/',
  path: '/pay-response/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OrdersRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCategoriesRoute = DashboardCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProductsNewRoute = DashboardProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardProductsRoute,
} as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/admin/orders/$orderId',
  path: '/admin/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/orders': typeof OrdersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/products': typeof DashboardProductsRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/pay-response': typeof PayResponseIndexRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/orders': typeof OrdersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/products': typeof DashboardProductsRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/pay-response': typeof PayResponseIndexRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/orders': typeof OrdersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/products': typeof DashboardProductsRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/pay-response/': typeof PayResponseIndexRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/orders'
    | '/profile'
    | '/auth/callback'
    | '/dashboard/categories'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/users'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/pay-response'
    | '/admin/orders/$orderId'
    | '/dashboard/products/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/orders'
    | '/profile'
    | '/auth/callback'
    | '/dashboard/categories'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/users'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/pay-response'
    | '/admin/orders/$orderId'
    | '/dashboard/products/new'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/orders'
    | '/profile'
    | '/auth/callback'
    | '/dashboard/categories'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/users'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/pay-response/'
    | '/admin/orders/$orderId'
    | '/dashboard/products/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  OrdersRoute: typeof OrdersRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  PayResponseIndexRoute: typeof PayResponseIndexRoute
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay-response/': {
      id: '/pay-response/'
      path: '/pay-response'
      fullPath: '/pay-response'
      preLoaderRoute: typeof PayResponseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products': {
      id: '/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/categories': {
      id: '/dashboard/categories'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof DashboardCategoriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/products/new': {
      id: '/dashboard/products/new'
      path: '/new'
      fullPath: '/dashboard/products/new'
      preLoaderRoute: typeof DashboardProductsNewRouteImport
      parentRoute: typeof DashboardProductsRoute
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/admin/orders/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardProductsRouteChildren {
  DashboardProductsNewRoute: typeof DashboardProductsNewRoute
}

const DashboardProductsRouteChildren: DashboardProductsRouteChildren = {
  DashboardProductsNewRoute: DashboardProductsNewRoute,
}

const DashboardProductsRouteWithChildren =
  DashboardProductsRoute._addFileChildren(DashboardProductsRouteChildren)

interface DashboardRouteChildren {
  DashboardCategoriesRoute: typeof DashboardCategoriesRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardProductsRoute: typeof DashboardProductsRouteWithChildren
  DashboardUsersRoute: typeof DashboardUsersRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCategoriesRoute: DashboardCategoriesRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardProductsRoute: DashboardProductsRouteWithChildren,
  DashboardUsersRoute: DashboardUsersRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface OrdersRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  OrdersRoute: OrdersRouteWithChildren,
  ProfileRoute: ProfileRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  PayResponseIndexRoute: PayResponseIndexRoute,
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
