/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as UnauthenticatedRouteImport } from './routes/_unauthenticated'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PayResponseIndexRouteImport } from './routes/pay-response/index'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as PaymentTransactionIdRouteImport } from './routes/payment.$transactionId'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedDashboardDashboardRouteImport } from './routes/_authenticated/dashboard/dashboard'
import { Route as AuthenticatedDashboardUsersIndexRouteImport } from './routes/_authenticated/dashboard/users/index'
import { Route as AuthenticatedDashboardProductsIndexRouteImport } from './routes/_authenticated/dashboard/products/index'
import { Route as AuthenticatedDashboardOrdersIndexRouteImport } from './routes/_authenticated/dashboard/orders/index'
import { Route as AuthenticatedDashboardCategoriesIndexRouteImport } from './routes/_authenticated/dashboard/categories/index'
import { Route as AuthenticatedDashboardProductsNewRouteImport } from './routes/_authenticated/dashboard/products/new'
import { Route as AuthenticatedAdminOrdersOrderIdRouteImport } from './routes/_authenticated/admin/orders/$orderId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayResponseIndexRoute = PayResponseIndexRouteImport.update({
  id: '/pay-response/',
  path: '/pay-response/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentTransactionIdRoute = PaymentTransactionIdRouteImport.update({
  id: '/payment/$transactionId',
  path: '/payment/$transactionId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OrdersRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardDashboardRoute =
  AuthenticatedDashboardDashboardRouteImport.update({
    id: '/dashboard/dashboard',
    path: '/dashboard/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardUsersIndexRoute =
  AuthenticatedDashboardUsersIndexRouteImport.update({
    id: '/dashboard/users/',
    path: '/dashboard/users/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardProductsIndexRoute =
  AuthenticatedDashboardProductsIndexRouteImport.update({
    id: '/dashboard/products/',
    path: '/dashboard/products/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardOrdersIndexRoute =
  AuthenticatedDashboardOrdersIndexRouteImport.update({
    id: '/dashboard/orders/',
    path: '/dashboard/orders/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardCategoriesIndexRoute =
  AuthenticatedDashboardCategoriesIndexRouteImport.update({
    id: '/dashboard/categories/',
    path: '/dashboard/categories/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardProductsNewRoute =
  AuthenticatedDashboardProductsNewRouteImport.update({
    id: '/dashboard/products/new',
    path: '/dashboard/products/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminOrdersOrderIdRoute =
  AuthenticatedAdminOrdersOrderIdRouteImport.update({
    id: '/admin/orders/$orderId',
    path: '/admin/orders/$orderId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/orders': typeof OrdersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/payment/$transactionId': typeof PaymentTransactionIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/pay-response': typeof PayResponseIndexRoute
  '/dashboard/dashboard': typeof AuthenticatedDashboardDashboardRoute
  '/admin/orders/$orderId': typeof AuthenticatedAdminOrdersOrderIdRoute
  '/dashboard/products/new': typeof AuthenticatedDashboardProductsNewRoute
  '/dashboard/categories': typeof AuthenticatedDashboardCategoriesIndexRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersIndexRoute
  '/dashboard/products': typeof AuthenticatedDashboardProductsIndexRoute
  '/dashboard/users': typeof AuthenticatedDashboardUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/orders': typeof OrdersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/payment/$transactionId': typeof PaymentTransactionIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/pay-response': typeof PayResponseIndexRoute
  '/dashboard/dashboard': typeof AuthenticatedDashboardDashboardRoute
  '/admin/orders/$orderId': typeof AuthenticatedAdminOrdersOrderIdRoute
  '/dashboard/products/new': typeof AuthenticatedDashboardProductsNewRoute
  '/dashboard/categories': typeof AuthenticatedDashboardCategoriesIndexRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersIndexRoute
  '/dashboard/products': typeof AuthenticatedDashboardProductsIndexRoute
  '/dashboard/users': typeof AuthenticatedDashboardUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_unauthenticated': typeof UnauthenticatedRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/orders': typeof OrdersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/payment/$transactionId': typeof PaymentTransactionIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/pay-response/': typeof PayResponseIndexRoute
  '/_authenticated/dashboard/dashboard': typeof AuthenticatedDashboardDashboardRoute
  '/_authenticated/admin/orders/$orderId': typeof AuthenticatedAdminOrdersOrderIdRoute
  '/_authenticated/dashboard/products/new': typeof AuthenticatedDashboardProductsNewRoute
  '/_authenticated/dashboard/categories/': typeof AuthenticatedDashboardCategoriesIndexRoute
  '/_authenticated/dashboard/orders/': typeof AuthenticatedDashboardOrdersIndexRoute
  '/_authenticated/dashboard/products/': typeof AuthenticatedDashboardProductsIndexRoute
  '/_authenticated/dashboard/users/': typeof AuthenticatedDashboardUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/orders'
    | '/profile'
    | '/auth/callback'
    | '/orders/$orderId'
    | '/payment/$transactionId'
    | '/products/$productId'
    | '/pay-response'
    | '/dashboard/dashboard'
    | '/admin/orders/$orderId'
    | '/dashboard/products/new'
    | '/dashboard/categories'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/orders'
    | '/profile'
    | '/auth/callback'
    | '/orders/$orderId'
    | '/payment/$transactionId'
    | '/products/$productId'
    | '/pay-response'
    | '/dashboard/dashboard'
    | '/admin/orders/$orderId'
    | '/dashboard/products/new'
    | '/dashboard/categories'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_unauthenticated'
    | '/cart'
    | '/checkout'
    | '/orders'
    | '/profile'
    | '/auth/callback'
    | '/orders/$orderId'
    | '/payment/$transactionId'
    | '/products/$productId'
    | '/pay-response/'
    | '/_authenticated/dashboard/dashboard'
    | '/_authenticated/admin/orders/$orderId'
    | '/_authenticated/dashboard/products/new'
    | '/_authenticated/dashboard/categories/'
    | '/_authenticated/dashboard/orders/'
    | '/_authenticated/dashboard/products/'
    | '/_authenticated/dashboard/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  UnauthenticatedRoute: typeof UnauthenticatedRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  PaymentTransactionIdRoute: typeof PaymentTransactionIdRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  PayResponseIndexRoute: typeof PayResponseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay-response/': {
      id: '/pay-response/'
      path: '/pay-response'
      fullPath: '/pay-response'
      preLoaderRoute: typeof PayResponseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/$transactionId': {
      id: '/payment/$transactionId'
      path: '/payment/$transactionId'
      fullPath: '/payment/$transactionId'
      preLoaderRoute: typeof PaymentTransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/dashboard': {
      id: '/_authenticated/dashboard/dashboard'
      path: '/dashboard/dashboard'
      fullPath: '/dashboard/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/users/': {
      id: '/_authenticated/dashboard/users/'
      path: '/dashboard/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof AuthenticatedDashboardUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/products/': {
      id: '/_authenticated/dashboard/products/'
      path: '/dashboard/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof AuthenticatedDashboardProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/orders/': {
      id: '/_authenticated/dashboard/orders/'
      path: '/dashboard/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof AuthenticatedDashboardOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/categories/': {
      id: '/_authenticated/dashboard/categories/'
      path: '/dashboard/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof AuthenticatedDashboardCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/products/new': {
      id: '/_authenticated/dashboard/products/new'
      path: '/dashboard/products/new'
      fullPath: '/dashboard/products/new'
      preLoaderRoute: typeof AuthenticatedDashboardProductsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/orders/$orderId': {
      id: '/_authenticated/admin/orders/$orderId'
      path: '/admin/orders/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedAdminOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardDashboardRoute: typeof AuthenticatedDashboardDashboardRoute
  AuthenticatedAdminOrdersOrderIdRoute: typeof AuthenticatedAdminOrdersOrderIdRoute
  AuthenticatedDashboardProductsNewRoute: typeof AuthenticatedDashboardProductsNewRoute
  AuthenticatedDashboardCategoriesIndexRoute: typeof AuthenticatedDashboardCategoriesIndexRoute
  AuthenticatedDashboardOrdersIndexRoute: typeof AuthenticatedDashboardOrdersIndexRoute
  AuthenticatedDashboardProductsIndexRoute: typeof AuthenticatedDashboardProductsIndexRoute
  AuthenticatedDashboardUsersIndexRoute: typeof AuthenticatedDashboardUsersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardDashboardRoute: AuthenticatedDashboardDashboardRoute,
  AuthenticatedAdminOrdersOrderIdRoute: AuthenticatedAdminOrdersOrderIdRoute,
  AuthenticatedDashboardProductsNewRoute:
    AuthenticatedDashboardProductsNewRoute,
  AuthenticatedDashboardCategoriesIndexRoute:
    AuthenticatedDashboardCategoriesIndexRoute,
  AuthenticatedDashboardOrdersIndexRoute:
    AuthenticatedDashboardOrdersIndexRoute,
  AuthenticatedDashboardProductsIndexRoute:
    AuthenticatedDashboardProductsIndexRoute,
  AuthenticatedDashboardUsersIndexRoute: AuthenticatedDashboardUsersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface OrdersRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  UnauthenticatedRoute: UnauthenticatedRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  OrdersRoute: OrdersRouteWithChildren,
  ProfileRoute: ProfileRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  PaymentTransactionIdRoute: PaymentTransactionIdRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  PayResponseIndexRoute: PayResponseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
